version: "3.3"

services:
  db:
    image: postgres:13-alpine
    container_name: trampoz-postgres
    restart: unless-stopped
    tty: true
    volumes:
      - ./sql-initial-files:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_USER: root
      POSTGRES_PASSWORD: db123
      POSTGRES_DB: trampoz
      LANG: pt_BR.UTF-8
    ports:
      - 5438:5432
    logging:
      options:
        max-size: "6m"
        max-file: "4"

  adminer:
    image: adminer
    container_name: trampoz-adminer
    restart: unless-stopped
    ports:
      - 9600:8080
    logging:
      options:
        max-size: "5m"
        max-file: "2"
